### PR TITLE
Finished Contact-us page

### PR DESCRIPTION
**Pull request by kaixuan98**
Finished all the element in contact-us page except scientist and mailing-list

### CODE REVIEW

**Comment by kaixuan98** [comment]
I am not sure why it show that there is a conflict with the master branch. Given that I merged by previous issue with the master only that I started to work on the new issues.

**Comment by rimapaul** [comment]
> I am not sure why it show that there is a conflict with the master branch. Given that I merged by previous issue with the master only that I started to work on the new issues.

I push something after you did, maybe that is why. `rebase` with master, it will probably help.

**Comment by kaixuan98** [comment]
Thank your for the note! I finished all the changes on both contact-us and join-us page.

**Comment by rimapaul** [comment]
I can't see any of the differences. Can you do a `git rebase master` than `git push --force-with-lease`?

**Comment by rimapaul** [comment]
I could see the changes now! The issue is: all the decorations are not in the contact us section, but below it, which extends the page.

**Comment by rimapaul** [comment]
The buttons look great!

**Comment by kaixuan98** [comment]
Yes, the decoration are all manually placed, I can't find a good way to make it dynamic. I can reposition them again.

**Comment by kaixuan98** [comment]
All the position are fixed.

**Comment by rimapaul** [comment]
@ishakantak Hey, why was this merged?

**Comment by ishakantak** [comment]
@rimapaul I am not sure, I think it was a mistake

**Pull request merged**
