### PR TITLE
Sponspors

### PR DESCRIPTION
**Pull request by johanotoka**
Added sponsors
Having issues issues extending the div's margin

### CODE REVIEW

**Comment by LauraTatianaToro** [comment]
Hey Steeve

Replace line 772 in index.html: `<div class="container w-container">`
with
`<div class="sponsor-content">`

And add styling like so:

.sponsor-content {
    width: 95%;
    height: 95%;
    margin-top: 40px;
    margin-bottom: 40px;
    background-color: #ffffff;
    border-radius: 27px;
}

Works for me:

image

**Comment by rimapaul** [comment]
> Hey Steeve
> 
> Replace line 772 in index.html: `<div class="container w-container">` with `<div class="sponsor-content">`
> 
> And add styling like so:
> 
> .sponsor-content { width: 95%; height: 95%; margin-top: 40px; margin-bottom: 40px; background-color: #ffffff; border-radius: 27px; }
> 
> Works for me:
> 
> image

Thanks @LauraTatianaToro!

**Comment by rimapaul** [comment]
Few little comments:
- can we have two logos per line, eg. Scotia and Telus next to each other. 
- instead of putting MLH under bronze, can we have another heading saying partners and put them under there

Looks good otherwise! :)

**Comment by johanotoka** [comment]
Thanks you so much @LauraTatianaToro !

Sure thing @rimapaul ! I'm gonna work on those points

**Pull request closed without merging**
